### ISSUE TITLE
firefox issue

### ISSUE THREAD

**Issue by SimHub** [developedbyed/3d-card-effect#2]
your 3d-card-effect work's fine in Chrome, Safari but not really in Firefox 🤔
Is there something I'am missing?

Anyway - great tut and content on your YT-Channel!

**Comment by m2paulc** [comment]
In firefox, the transform-style attribute is not inherited, therefore must be declared for each container descendent. I have sent a PR to fix this issue.

**Comment by WiZzHarDJo** [comment]
@m2paulc thanks for the pr, the ztransform now works in firefox ! I was just wondering if you knew why the animations seem less punchy in firefox than in chrome ? In firefox it's lagging a little (the ease-in is not as smooth) and the mouse events are less detected. Is it a known issue about firefox ? Thanks !

**Comment by m2paulc** [comment]
@WiZzHarDJo, I'm not really sure about the lagging. When I was testing it, it seems to be fine. I didn't experience the laggy animation in firefox. I do know that the transition attribute is with the "ease-out" property. You may want to try that and see if that makes a difference.

**Comment by SimHub** [comment]
Thank's @WiZzHarDJo , It works 🙂
